# Dockerfile.airflow
FROM apache/airflow:2.8.1
USER root
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean
USER airflow
RUN pip install apache-airflow-providers-apache-spark
RUN pip install openlineage-airflow>=1.37.0
RUN pip install openlineage-python>=1.37.0
